In [1]:
import uproot

# Open the ROOT file and access the tree
with uproot.open("scorefile.root") as file:
    tree = file["Events"]

In [2]:
df = tree.arrays(["EventID", "Timestamp", "En_dep", "Scint_ID", "X_Detected", "Y_Detected", "Z_Detected"], library="pd")
df

,EventID,Timestamp,En_dep,Scint_ID,X_Detected,Y_Detected,Z_Detected
0,7,18.841256,8.345201,6,-12.442033,10.521104,13.782759
1,7,18.841256,0.454739,1,-7.942033,10.521104,9.282759
2,7,18.841256,41.195342,5,-9.592033,10.521104,34.182758
3,13,23.725272,0.982522,22,-21.442033,10.521104,-9.417241
4,15,25.203937,0.820748,34,6.257967,10.521104,-4.917241
5,15,25.203937,44.663531,1,31.157967,10.521104,3.832759
6,16,26.697356,38.679474,4,4.607967,10.521104,34.182758
7,18,28.999450,47.368166,14,-32.842033,10.521104,-13.667241
8,20,30.591924,5.589504,18,-7.942033,10.521104,-4.917241
9,20,30.591924,40.656073,22,-13.392033,10.521104,-29.817242
10,21,31.777710,11.911134,25,-12.442033,10.521104,-4.917241
11,21,31.777710,38.088196,22,-13.392033,10.521104,-29.817242
12,25,33.956727,2.638820,50,6.257967,10.521104,9.282759
13,25,33.956727,1.995326,5,-12.442033,10.521104,18.282759
14,25,33.956727,45.365853,7,-16.692033,10.521104,34.182758

In [3]:
# Comparison with the input CSV file
import pandas as pd

df = pd.read_csv("rsm-events.csv")

rows = df.iloc[[7, 13, 15]]
print(rows)

    event_id       time     angle     pol_x  pol_y     pol_z  energy
7          7  18.841256  1.183831  0.377380    0.0  0.926059    50.0
13        13  23.725272  1.490703  0.080008    0.0  0.996794    50.0
15        15  25.203937  1.583610 -0.012813    0.0  0.999918    50.0